---
- hosts: eos
  gather_facts: no
  connection: nework_cli
  become: yes


      

  tasks:
  
  - name: show file systems
    eos_command:
      authorize: yes
      commands:
        - "show file systems | json"
    register: file_systems


  - debug:
      msg: "{{ file_systems.stdout_lines[0].fileSystems | json_query(_q1) }}"
    vars:
      _q1: "[?prefix=='flash:'].{ size: size }"
  
  
