---
- hosts: eos
  gather_facts: no
  connection: nework_cli
  become: yes

      

  tasks:
  
  - name: show interfaces
    eos_command:
      authorize: yes
      commands:
        - "show interfaces | json"
    register: interfaces


#  - debug: var=interfaces
  
  
  - set_fact: 
      cached_interfaces: "{{ interfaces }}"
      
      
      
 # - debug: var=cached_interfaces
  
  
  - debug: var=cached_interfaces.stdout.0.interfaces.Ethernet1
