---
- hosts: eos
  gather_facts: no
  connection: nework_cli

      

  tasks:
  
  - name: get the current name-server configs
    eos_command:
      commands:
        - "show interfaces | json"
    register: interfaces


  - debug: var=interfaces
  
  
  - set_fact: 
      interfaces: cached_interfaces
      
      
  - debug: var=cached_interfaces
